# $EXT_DB/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1  # <-- Component notation
kind: Component

secretGenerator:
- name: dbpass
  files:
    - dbpass.txt

patchesStrategicMerge:
  - configmap-patch.yaml

patchesJson6902:
- target:
# group and version matche the `apiVersion: apps/v1`; can be omited if kind and name is uniquely matched
    group: apps
    version: v1
    kind: Deployment
    name: example
  path: deployment-patch.yaml
