# $EXT_DB/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1  # <-- Component notation
kind: Component

secretGenerator:
# from a file generate secret named `dbpass`
# TODO which other input accepted than `files`?
- name: dbpass
  files:
    - dbpass.txt

patchesStrategicMerge:
# read the local file configmap-patch.yaml and patch it to existing configmap using merge.
  - configmap-patch.yaml

patchesJson6902:
# Define a set of patches named `patchesJson6902`. The name is arbitrary (not sure what else supported)
- target:
# group and version match the `apiVersion: apps/v1`; can be omited if kind and name is uniquely matched
    group: apps
    version: v1
    kind: Deployment
    name: example
  # local file to describe the ops
  path: deployment-patch.yaml
